# Generated by Django 2.2.5 on 2019-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("indicators", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="person", name="city"),
        migrations.RemoveField(model_name="person", name="country"),
        migrations.AddField(
            model_name="country",
            name="label",
            field=models.CharField(default="abv", max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="country", name="name", field=models.CharField(max_length=100)
        ),
        migrations.DeleteModel(name="City"),
        migrations.DeleteModel(name="Person"),
    ]
